name: JavaScript Lint and Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**.ts'
      - '**.js'
      - '**.html'
      - '**.svelte'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint-js:
    name: JavaScript Lint
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Sync Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package.lock') }}
          restore-keys: ${{ runner.os }}-npm-dependencies

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Instal npm dependencies
        run: npm install

      - name: Run JS linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test:unit
